

import type { NavLink, Page, User, ProjectData, ProjectOfficerRole } from './types';

export const NAV_LINKS: NavLink[] = [
  { href: "#", icon: "fas fa-home", labelKey: "dashboard" },
  
  // ADMIN ONLY
  { type: "header", href: "#", icon: "fas fa-shield-alt", labelKey: "adminReports", adminOnly: true },
  { href: "#", icon: "fas fa-list-alt", labelKey: "adminAllProjects", adminOnly: true },
  { href: "#", icon: "fas fa-car-side", labelKey: "adminAllVehicles", adminOnly: true },
  { href: "#", icon: "fas fa-exclamation-triangle", labelKey: "adminAllIncidents", adminOnly: true },
  { href: "#", icon: "fas fa-route", labelKey: "adminTransferLog", adminOnly: true },

  // USER LINKS
  { type: "header", href: "#", icon: "fas fa-users", labelKey: "menPower" },
  { href: "#", icon: "fas fa-user-plus", labelKey: "addSupervisor" },
  { href: "#", icon: "fas fa-tasks", labelKey: "supervisorOverview" },
  { type: "header", href: "#", icon: "fas fa-user-tie", labelKey: "projectOfficersHeader" },
  { href: "#", icon: "fas fa-user-edit", labelKey: "addProjectOfficers" },
  { href: "#", icon: "fas fa-file-alt", labelKey: "viewProjectOfficers" },
  { type: "header", href: "#", icon: "fas fa-car", labelKey: "vehicleFleet" },
  { href: "#", icon: "fas fa-car", labelKey: "addVehicle" },
  { href: "#", icon: "fas fa-list", labelKey: "viewVehicles" },
  { href: "#/add-driver", icon: "fas fa-user-plus", labelKey: "addDriver" },
  { href: "#/view-drivers", icon: "fas fa-users", labelKey: "viewDrivers" },
  { href: "#", icon: "fas fa-exchange-alt", labelKey: "transferVehicle"},
  { href: "#", icon: "fas fa-car-crash", labelKey: "reportIncident" },
  { href: "#", icon: "fas fa-chart-line", labelKey: "reports" },
  { href: "#", icon: "fas fa-cog", labelKey: "settings" },
  { href: "#", icon: "fas fa-sign-out-alt", labelKey: "logout" },
];

export const PROJECT_OFFICER_ROLES: ProjectOfficerRole[] = [
    'Project Manager',
    'Assistant Project Manager',
    'Operation Manager',
    'Admin Manager',
    'Camp Boss',
    'Fleet Manager',
    'Haraka Supervisor 1',
    'Haraka Supervisor 2'
];

export const SERVICE_TYPES = {
    en: [
        'Bulk Waste Collection',
        'Emergency CWC Service',
        'Recyclable Waste',
        'Litter Picking',
        'Street Sweeping',
        'Container Maintenance',
        'Container Cleaning',
        'CWC (REL) Service',
        'Container Washing Truck',
        'Container Distribution Truck',
        'Roads & Sidewalks Washing Vehicle',
        'Mechanical Sweeper',
        'Pavement Sweeping Machine',
        'Sanitation Machine',
        'Small Sweeper',
        'Trailer Sweeper',
        'Litter Suction Machine',
        'Wheel Loader',
        'Dump Truck',
        'Roll On/Off - Lugger',
        'Solid Waste Chopper/Shredder Machine',
        'Trees & Wood Chopper/Shredder Machine',
        'Other'
    ],
    ar: [
        'جمع النفايات الكبيرة',
        'خدمة الطوارئ CWC',
        'النفايات القابلة لإعادة التدوير',
        'جمع النفايات المتناثرة',
        'كنس الشوارع',
        'صيانة الحاويات',
        'غسيل الحاويات',
        'خدمة CWC (REL)',
        'شاحنة غسيل الحاويات',
        'شاحنة توزيع الحاويات',
        'مركبة غسيل الطرق والأرصفة',
        'مكنسة ميكانيكية',
        'آلة كنس الأرصفة',
        'آلة التعقيم',
        'مكنسة صغيرة',
        'مكنسة مقطورة',
        'آلة شفط النفايات',
        'جرافة (لودر بعجلات)',
        'شاحنة قلّاب',
        'شاحنة رول أون/أوف (لوغر)',
        'آلة فرم النفايات الصلبة',
        'آلة تقطيع وفرم الأشجار والأخشاب',
        'أخرى'
    ]
};

export const CHART_COLORS = [
    '#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#38BDF8',
    '#F97316', '#EC4899', '#6366F1', '#14B8A6', '#D946EF', '#0EA5E9'
];

// Vehicle type categories for stacked chart
export const VEHICLE_TYPE_COLORS = {
    'Car': '#3B82F6',      // Blue
    'Truck': '#10B981',    // Green  
    'Van': '#F59E0B',      // Orange
    'Motorcycle': '#8B5CF6', // Purple
    'Other': '#EF4444'     // Red
};

// Mapping service types to vehicle categories
export const SERVICE_TYPE_TO_CATEGORY: Record<string, string> = {
    // Cars/Light Vehicles
    'Bulk Waste Collection': 'Car',
    'Emergency CWC Service': 'Car',
    'Litter Picking': 'Car',
    'CWC (REL) Service': 'Car',
    
    // Trucks
    'Container Washing Truck': 'Truck',
    'Container Distribution Truck': 'Truck',
    'Dump Truck': 'Truck',
    'Roll On/Off - Lugger': 'Truck',
    'Wheel Loader': 'Truck',
    
    // Vans
    'Recyclable Waste': 'Van',
    'Container Maintenance': 'Van',
    'Container Cleaning': 'Van',
    'Roads & Sidewalks Washing Vehicle': 'Van',
    
    // Motorcycles/Small Vehicles
    'Street Sweeping': 'Motorcycle',
    'Pavement Sweeping Machine': 'Motorcycle',
    'Small Sweeper': 'Motorcycle',
    
    // Other/Specialized Equipment
    'Mechanical Sweeper': 'Other',
    'Sanitation Machine': 'Other',
    'Trailer Sweeper': 'Other',
    'Litter Suction Machine': 'Other',
    'Solid Waste Chopper/Shredder Machine': 'Other',
    'Trees & Wood Chopper/Shredder Machine': 'Other',
    'Other': 'Other',
    'Unspecified': 'Other'
};

export const MOCK_USERS: User[] = [
    {
        uid: 'admin-001',
        email: 'zahran@projects.reports',
        password: 'zahran111',
        isAdmin: true,
        projectName: 'Zahran Admin',
        projectManagerName: 'Admin',
        projectId: 'ADM-001',
        operatorName: 'Admin'
    }
];

export const MOCK_PROJECT_DATA: Record<string, Omit<ProjectData, 'supervisors' | 'notifications' | 'projectOfficers'>> = {};


export const TRANSLATIONS = {
    en: {
        // Auth
        loginTitle: "Sign In",
        signUpTitle: "Create Account",
        email: "Email Address",
        password: "Password",
        confirmPassword: "Confirm Password",
        projectName: "Project Name",
        projectManagerName: "Project Manager Name",
        projectId: "Project ID",
        operatorName: "Data Entry Operator Name",
        createAccount: "Create Account",
        signIn: "Sign In",
        dontHaveAccount: "Don't have an account?",
        signUpHere: "Sign Up",
        alreadyHaveAccount: "Already have an account?",
        signInHere: "Sign In",
        accountCreatedSuccess: "Account created successfully! Please sign in.",
        invalidCredentials: "Invalid email or password.",
        emailInvalid: "Please enter a valid email address.",
        passwordInvalid: "Password must be at least 8 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        welcome: "Welcome",
        forgotPassword: "Forgot Password?",
        forgotPasswordTitle: "Reset Password",
        forgotPasswordInstructions: "Enter your email address to start the password reset process.",
        sendResetLink: "Reset Password",
        resetEmailSent: "If an account with that email exists, a password reset link has been sent.",
        backToLogin: "Back to Login",
        adminLogin: "Admin Login",
        adminLoginHint: "Please enter the admin email and password.",
        tooManyRequests: "Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.",
        genericAuthError: "An unexpected error occurred. Please try again.",
        
        // Security Questions
        securityQuestion: "Security Question",
        securityAnswer: "Security Answer",
        companyNameQuestion: "What is your company name?",
        securityQuestionRequired: "Security answer is required",
        invalidSecurityAnswer: "Incorrect security answer",
        passwordResetSuccess: "Password reset successful! You can now login with your new password.",
        newPassword: "New Password",
        passwordResetTitle: "Reset Your Password",
        next: "Next",
        
        // App
        appName: "Environmental Services Zahran Fleet",
        dashboard: "Dashboard",
        addVehicle: "Add Vehicle",
        viewVehicles: "View Vehicles",
        viewVehicleDetails: "Vehicle Details",
        addDriver: "Add Driver",
        viewDrivers: "View Drivers",
        transferVehicle: "Transfer Vehicle",
        reportIncident: "Report Incident",
        reports: "Reports",
        settings: "Settings",
        logout: "Logout",
        addDriverTitle: "Add New Driver",
        driverInfo: "Driver Information",
        driverName: "Driver Name",
        nationality: "Nationality",
        driverIqama: "Driver's Iqama Number",
        driverMobile: "Driver's Mobile Number",
        assignVehicle: "Assign Vehicle",
        assignedVehicle: "Assigned Vehicle (Door Number)",
        selectVehicleOptional: "Select a vehicle (Optional)",
        searchVehicleHint: "Type door number, plate number, or chassis number to search.",
        cancel: "Cancel",
        saveDriver: "Save Driver",
        saveSuccess: "Driver saved successfully!",
        saveError: "Error saving driver. Please check the form for errors.",
        requiredField: "This field is required.",
        vehicleAlreadyAssigned: "This vehicle is already assigned to another driver.",
        doorNumberExists: "This door number is already registered in the system.",
        iqamaInvalid: "Please enter a valid 10-digit Iqama number.",
        mobileInvalid: "Please enter a valid Saudi mobile number starting with 5.",
        noVehiclesFound: "No vehicles found.",
        vehicleSearchPlaceholder: "Search vehicle...",
        viewDriversTitle: "View Drivers",
        searchByNameOrIqama: "Search by name or Iqama...",
        noDriversFound: "No drivers found.",
        thDriverName: "Driver Name",
        thIqama: "Iqama",
        thMobile: "Mobile",
        thAssignedVehicle: "Assigned Vehicle",
        unassigned: "Unassigned",
        actions: "Actions",
        addVehicleTitle: "Add New Vehicle / Equipment",
        vehicleInfo: "Vehicle / Equipment Information",
        doorNumber: "Door Number",
        plateNumber: "Plate Number",
        chassisNumber: "Chassis Number",
        saveVehicle: "Save Vehicle",
        saveVehicleSuccess: "Vehicle saved successfully!",
        make: "Make / Model",
        manufacturer: "Manufacturer",
        projectSite: "Project Site / Area",
        year: "Year",
        purchaseDate: "Purchase Date",
        tareWeight: "Tare Weight (KG)",
        serviceType: "Service Type",
        otherServiceType: "Other Service Type",
        viewVehiclesTitle: "View Vehicles / Equipment",
        searchByDoorPlateChassis: "Search by Door, Plate, or Chassis...",
        thDoorNumber: "Door #",
        thPlateNumber: "Plate #",
        thChassisNumber: "Chassis #",
        thMake: "Make / Model",
        thManufacturer: "Manufacturer",
        thProjectSite: "Project Site",
        thYear: "Year",
        thPurchaseDate: "Purchase Date",
        thTareWeight: "Tare Weight",
        thServiceType: "Service Type",
        thStatus: "Status",
        total: "Total",
        vehicles: "Vehicles",
        showDetails: "Show Details",
        hideDetails: "Hide Details",
        totalVehicles: "Total Vehicles",
        totalDrivers: "Total Drivers",
        unassignedVehicles: "Unassigned Vehicles",
        vehiclesInWorkshop: "Vehicles in Workshop",
        vehiclesByArea: "Vehicles by Project Site",
        driversByNationality: "Drivers by Nationality",
        addedNewVehicle: "Added new vehicle",
        addedNewDriver: "Added new driver",
        noRecentActivity: "No recent activity to display.",
        vehicleDetailsTitle: "Vehicle / Equipment Details",
        assignedDriver: "Assigned Driver",
        searchByDoorNumber: "Enter Door Number...",
        search: "Search",
        vehicleDetailsSearchPrompt: "Search for a vehicle by its door number to see details.",
        vehicleNotFound: "Vehicle with this door number not found.",
        noVehicleSelected: "Please select a vehicle from the 'View Vehicles' list to see its details.",
        viewDetails: "View Details",
        editVehicleTitle: "Edit Vehicle / Equipment",
        saveChanges: "Save Changes",
        delete: "Delete",
        deleteVehicleTitle: "Delete Vehicle",
        deleteVehicleMessage: "Are you sure you want to delete this vehicle? This action cannot be undone.",
        confirmDelete: "Yes, Delete",
        editDriverTitle: "Edit Driver",
        deleteDriverTitle: "Delete Driver",
        deleteDriverMessage: "Are you sure you want to delete this driver?",
        deleteSelected: "Delete Selected ({count})",
        deleteSelectedItemsTitle: "Delete Selected Items",
        deleteSelectedItemsMessage: "Are you sure you want to delete the {count} selected items? This action cannot be undone.",
        event: "Event",
        timestamp: "Timestamp",
        details: "Details",
        settingsTitle: "Settings",
        languageSettings: "Language Settings",
        chooseLanguage: "Choose your preferred language.",
        english: "English",
        arabic: "Arabic",
        themeSettings: "Theme Settings",
        lightMode: "Light",
        darkMode: "Dark",
        adminPasswordSettings: "Project Password Management",
        manageProjectPasswords: "Manage Project Passwords",
        managePasswordsDescription: "Set or update passwords for all saved projects",
        managePasswordsButton: "Manage Passwords",
        projectPasswordManagementTitle: "Project Password Management",
        currentPassword: "Current Password",
        updatePassword: "Update Password",
        updateAllPasswords: "Update All Passwords",
        setGlobalPassword: "Set Global Password",
        setGlobalPasswordDescription: "Set the same password for all projects",
        globalPasswordPlaceholder: "Enter global password for all projects",
        passwordUpdatedSuccess: "Password updated successfully!",
        allPasswordsUpdatedSuccess: "All project passwords updated successfully!",
        passwordUpdateError: "Error updating password. Please try again.",
        needHelp: "Need Help?",
        whatsappSupport: "Contact Support on WhatsApp",
        whatsappSupportDescription: "If you're unable to reset your password, contact our support team on WhatsApp for assistance.",
        contactSupport: "Contact Support",
        reportIncidentTitle: "Report Vehicle Incident",
        incidentInfo: "Incident Information",
        selectVehicle: "Select Vehicle",
        incidentType: "Incident Type",
        accident: "Accident",
        notWorking: "Not Working",
        incidentDate: "Incident Date",
        description: "Description",
        submitReport: "Submit Report",
        reportSuccess: "Incident report submitted successfully!",
        status_Active: "Active",
        status_Accident: "Accident",
        status_Not_Working: "Not Working",
        reportsTitle: "Incident Reports",
        thVehicle: "Vehicle",
        thIncidentType: "Incident Type",
        thIncidentDate: "Date",
        thDescription: "Description",
        noIncidentsFound: "No incidents reported yet.",
        import: "Import",
        importVehicles: "Import Vehicles",
        importDrivers: "Import Drivers",
        importSuccess: "Data imported successfully!",
        importError: "Failed to import data. Please check the file format and content.",
        thAssignedVehicleDoorNumber: "Assigned Vehicle Door Number",
        
        // Transfers
        transferVehicleTitle: "Transfer Vehicle",
        transferInfo: "Transfer Information",
        currentProject: "Current Project",
        transferTo: "Transfer To",
        transferDate: "Transfer Date & Time",
        selectProject: "Select a destination project...",
        confirmTransfer: "Confirm Transfer",
        transferSuccess: "Vehicle transferred successfully!",
        transferError: "Error transferring vehicle.",
        transferHistory: "Transfer History",
        noTransfersFound: "No transfer history found.",
        thFromProject: "From Project",
        thToProject: "To Project",
        status_Transferred: "Transferred",
        status_Returned: "Returned",
        notifyAdmin: "Notify Admin",
        notifyAdminSent: "Notify Sent",
        notifyAdminReturned: "Notify Returned",
        notified: "Notified",
        notificationSent: "Admin has been notified.",
        deleteTransferTitle: "Delete Transfer",
        deleteTransferMessage: "Are you sure you want to delete this transfer record? This action cannot be undone.",

        // Admin
        adminDashboard: "Dashboard",
        totalProjects: "Total Projects",
        allProjectsReport: "All Projects Report",
        allIncidentsReport: "All Incidents Report",
        allVehiclesReport: "All Vehicles Report",
        viewProjectDashboard: "View Dashboard",
        thProjectName: "Project Name",
        thProjectManager: "Manager",
        thProjectId: "Project ID",
        totalIncidents: "Total Incidents",
        globalVehicleSearch: "Global Vehicle Search",
        searchByDoorNumberAdmin: "Search by Door Number...",
        globalDriverSearch: "Global Driver Search",
        searchByIqama: "Search by Iqama Number...",
        vehicleFoundIn: "Vehicle Found in Project",
        driverFoundIn: "Driver Found in Project",
        driverNotFound: "Driver with this Iqama number not found.",
        vehiclesByServiceType: "Vehicles by Service Type",
        totalVehiclesByProject: "Total Vehicles by Project",
        totalVehiclesByProjectAndType: "Total Vehicles by Project & Type",
        allProjects: "All Projects",
        filterByProject: "Filter by Project...",
        transferLog: "Transfer Log",
        transferNotifications: "Transfer Notifications",
        dismissNotification: "Dismiss",
        noNewNotifications: "No new notifications.",
        clearAll: "Clear All",
        clearAllNotificationsTitle: "Clear All Notifications",
        clearAllNotificationsMessage: "Are you sure you want to permanently delete all notifications?",
        adminReports: "Reports",
        adminTransferLog: "Transfers",
        adminAllProjects: "Projects",
        adminAllIncidents: "Incidents",
        adminAllVehicles: "Vehicles",

        // Man Power
        menPower: "Man Power",
        addSupervisor: "Add Supervisor",
        supervisorOverview: "Supervisor Overview",
        addSupervisorTitle: "Add New Supervisor",
        supervisorInfo: "Supervisor Information",
        supervisorName: "Supervisor Name",
        areaLocation: "Area / Location",
        supervisorIqama: "Supervisor's Iqama Number",
        supervisorMobile: "Supervisor's Mobile Number",
        foremenInfo: "Foremen Information",
        addForeman: "Add Foreman",
        foremanName: "Foreman Name",
        totalAssignedLabour: "Total Assigned Labour",
        saveSupervisor: "Save Supervisor",
        supervisorSaveSuccess: "Supervisor and foremen saved successfully!",
        supervisorUpdateSuccess: "Supervisor updated successfully!",
        supervisorOverviewTitle: "Man Power Overview",
        campLabour: "Camp Labour",
        crewman: "Crewman",
        totalLabour: "Total Labour",
        manpowerBySupervisor: "Manpower by Supervisor",
        workers: "Workers",
        noSupervisorsFound: "No supervisors have been added yet.",
        totalSupervisors: "Total Supervisors",
        totalForemen: "Total Foremen",
        projectLevelLabour: "Project Level Labour",
        vehicleFleet: "Vehicle Fleet",
        manPowerStatistics: "Man Power Statistics",
        editSupervisorTitle: "Edit Supervisor",
        deleteSupervisorTitle: "Delete Supervisor",
        deleteSupervisorMessage: "Are you sure you want to delete this supervisor and all associated foremen?",

        // Project Officers
        projectOfficersHeader: "Project Officers",
        addProjectOfficers: "Add/Edit Officers",
        viewProjectOfficers: "View Officers Report",
        officerRole_Project_Manager: "Project Manager",
        officerRole_Assistant_Project_Manager: "Assistant Project Manager",
        officerRole_Operation_Manager: "Operation Manager",
        officerRole_Admin_Manager: "Admin Manager",
        officerRole_Camp_Boss: "Camp Boss",
        officerRole_Fleet_Manager: "Fleet Manager",
        officerRole_Haraka_Supervisor_1: "Haraka Supervisor 1",
        officerRole_Haraka_Supervisor_2: "Haraka Supervisor 2",
        officerRole: "Officer Role",
        officerName: "Name",
        officerIqama: "Iqama Number",
        officerMobile: "Mobile Number",
        updateOfficers: "Update Officers",
        officersUpdateSuccess: "Project officers updated successfully!",
        exportOfficers: "Export Officers Report",
        noOfficersFound: "No project officers have been added yet.",
        projectOfficersReport: "Project Officers Report",
        addOfficer: "Add Officer",
        deleteOfficerTitle: "Delete Officer",
        deleteOfficerMessage: "Are you sure you want to delete this officer?",

        // Project Names (for programmatic lookup)
        projectName_Riyadh_Site_Project: "Riyadh Site Project",
        projectName_Jeddah_Expansion: "Jeddah Expansion",
    },
    ar: {
        // Auth
        loginTitle: "تسجيل الدخول",
        signUpTitle: "إنشاء حساب",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        confirmPassword: "تأكيد كلمة المرور",
        projectName: "اسم المشروع",
        projectManagerName: "اسم مدير المشروع",
        projectId: "معرف المشروع",
        operatorName: "اسم مدخل البيانات",
        createAccount: "إنشاء حساب",
        signIn: "تسجيل الدخول",
        dontHaveAccount: "ليس لديك حساب؟",
        signUpHere: "سجل هنا",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        signInHere: "سجل الدخول",
        accountCreatedSuccess: "تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.",
        invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
        emailInvalid: "الرجاء إدخال عنوان بريد إلكتروني صالح.",
        passwordInvalid: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
        passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.",
        welcome: "أهلاً بك",
        forgotPassword: "هل نسيت كلمة المرور؟",
        forgotPasswordTitle: "إعادة تعيين كلمة المرور",
        forgotPasswordInstructions: "أدخل عنوان بريدك الإلكتروني لبدء عملية إعادة تعيين كلمة المرور.",
        sendResetLink: "إعادة تعيين كلمة المرور",
        resetEmailSent: "إذا كان هناك حساب بهذا البريد الإلكتروني، فقد تم إرسال رابط إعادة تعيين كلمة المرور.",
        backToLogin: "العودة لتسجيل الدخول",
        adminLogin: "دخول المسؤول",
        
        // Security Questions Arabic
        securityQuestion: "السؤال الأمني",
        securityAnswer: "الإجابة الأمنية",
        companyNameQuestion: "ما هو اسم شركتك؟",
        securityQuestionRequired: "الإجابة الأمنية مطلوبة",
        invalidSecurityAnswer: "إجابة أمنية خاطئة",
        passwordResetSuccess: "تم إعادة تعيين كلمة المرور بنجاح! يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
        newPassword: "كلمة المرور الجديدة",
        passwordResetTitle: "إعادة تعيين كلمة المرور",
        next: "التالي",
        adminLoginHint: "الرجاء إدخال البريد الإلكتروني وكلمة المرور الخاصة بالمسؤول.",
        tooManyRequests: "تم تعطيل الوصول إلى هذا الحساب مؤقتًا بسبب العديد من محاولات تسجيل الدخول الفاشلة. يمكنك استعادته فورًا عن طريق إعادة تعيين كلمة المرور أو يمكنك المحاولة مرة أخرى لاحقًا.",
        genericAuthError: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",

        // App
        appName: "أسطول زهران للخدمات البيئية",
        dashboard: "لوحة التحكم",
        addVehicle: "إضافة سيارة",
        viewVehicles: "عرض السيارات",
        viewVehicleDetails: "تفاصيل السيارة",
        addDriver: "إضافة سائق",
        viewDrivers: "عرض السائقين",
        transferVehicle: "نقل سيارة",
        reportIncident: "الإبلاغ عن حادث",
        reports: "التقارير",
        settings: "الإعدادات",
        logout: "تسجيل خروج",
        addDriverTitle: "إضافة سائق جديد",
        driverInfo: "معلومات السائق",
        driverName: "اسم السائق",
        nationality: "الجنسية",
        driverIqama: "رقم إقامة السائق",
        driverMobile: "رقم جوال السائق",
        assignVehicle: "تعيين سيارة",
        assignedVehicle: "السيارة المعينة (رقم الباب)",
        selectVehicleOptional: "اختر سيارة (اختياري)",
        searchVehicleHint: "اكتب رقم الباب أو رقم اللوحة أو رقم الهيكل للبحث.",
        cancel: "إلغاء",
        saveDriver: "حفظ السائق",
        saveSuccess: "تم حفظ السائق بنجاح!",
        saveError: "حدث خطأ أثناء حفظ السائق. يرجى التحقق من الحقول.",
        requiredField: "هذا الحقل مطلوب.",
        vehicleAlreadyAssigned: "هذه السيارة معينة بالفعل لسائق آخر.",
        doorNumberExists: "رقم الباب هذا مسجل بالفعل في النظام.",
        iqamaInvalid: "الرجاء إدخال رقم إقامة صحيح مكون من 10 أرقام.",
        mobileInvalid: "الرجاء إدخال رقم جوال سعودي صحيح يبدأ بـ 5.",
        noVehiclesFound: "لم يتم العثور على سيارات.",
        vehicleSearchPlaceholder: "ابحث عن سيارة...",
        viewDriversTitle: "عرض السائقين",
        searchByNameOrIqama: "ابحث بالاسم أو رقم الإقامة...",
        noDriversFound: "لم يتم العثور على سائقين.",
        thDriverName: "اسم السائق",
        thIqama: "الإقامة",
        thMobile: "الجوال",
        thAssignedVehicle: "السيارة المعينة",
        unassigned: "غير معين",
        actions: "إجراءات",
        addVehicleTitle: "إضافة سيارة / معدات جديدة",
        vehicleInfo: "معلومات السيارة / المعدات",
        doorNumber: "رقم الباب",
        plateNumber: "رقم اللوحة",
        chassisNumber: "رقم الهيكل",
        saveVehicle: "حفظ السيارة",
        saveVehicleSuccess: "تم حفظ السيارة بنجاح!",
        make: "النوع / الموديل",
        manufacturer: "الشركة المصنعة",
        projectSite: "موقع المشروع / المنطقة",
        year: "سنة الصنع",
        purchaseDate: "تاريخ الشراء",
        tareWeight: "الوزن الفارغ (كجم)",
        serviceType: "سيارة الخدمة",
        otherServiceType: "سيارة خدمة أخرى",
        viewVehiclesTitle: "عرض السيارات / المعدات",
        searchByDoorPlateChassis: "ابحث برقم الباب، اللوحة، أو الهيكل...",
        thDoorNumber: "رقم الباب",
        thPlateNumber: "رقم اللوحة",
        thChassisNumber: "رقم الهيكل",
        thMake: "النوع / الموديل",
        thManufacturer: "الشركة المصنعة",
        thProjectSite: "موقع المشروع",
        thYear: "سنة الصنع",
        thPurchaseDate: "تاريخ الشراء",
        thTareWeight: "الوزن الفارغ",
        thServiceType: "سيارة الخدمة",
        thStatus: "الحالة",
        total: "الإجمالي",
        vehicles: "السيارات",
        showDetails: "إظهار التفاصيل",
        hideDetails: "إخفاء التفاصيل",
        totalVehicles: "إجمالي السيارات",
        totalDrivers: "إجمالي السائقين",
        unassignedVehicles: "سيارات غير معينة",
        vehiclesInWorkshop: "سيارات في الورشة",
        vehiclesByArea: "السيارات حسب موقع المشروع",
        driversByNationality: "السائقون حسب الجنسية",
        addedNewVehicle: "تمت إضافة سيارة جديدة",
        addedNewDriver: "تمت إضافة سائق جديد",
        noRecentActivity: "لا يوجد نشاط أخير لعرضه.",
        vehicleDetailsTitle: "تفاصيل السيارة / المعدات",
        assignedDriver: "السائق المعين",
        searchByDoorNumber: "أدخل رقم الباب...",
        search: "بحث",
        vehicleDetailsSearchPrompt: "ابحث عن سيارة برقم بابها لعرض التفاصيل.",
        vehicleNotFound: "لم يتم العثور على سيارة بهذا الرقم.",
        noVehicleSelected: "يرجى اختيار سيارة من قائمة 'عرض السيارات' لعرض تفاصيلها.",
        viewDetails: "عرض التفاصيل",
        editVehicleTitle: "تعديل السيارة / المعدات",
        saveChanges: "حفظ التغييرات",
        delete: "حذف",
        deleteVehicleTitle: "حذف السيارة",
        deleteVehicleMessage: "هل أنت متأكد أنك تريد حذف هذه السيارة؟ لا يمكن التراجع عن هذا الإجراء.",
        confirmDelete: "نعم، احذف",
        editDriverTitle: "تعديل السائق",
        deleteDriverTitle: "حذف السائق",
        deleteDriverMessage: "هل أنت متأكد أنك تريد حذف هذا السائق؟",
        deleteSelected: "حذف المحدد ({count})",
        deleteSelectedItemsTitle: "حذف العناصر المحددة",
        deleteSelectedItemsMessage: "هل أنت متأكد أنك تريد حذف {count} من العناصر المحددة؟ لا يمكن التراجع عن هذا الإجراء.",
        event: "الحدث",
        timestamp: "الوقت",
        details: "التفاصيل",
        settingsTitle: "الإعدادات",
        languageSettings: "إعدادات اللغة",
        chooseLanguage: "اختر لغتك المفضلة.",
        english: "الإنجليزية",
        arabic: "العربية",
        themeSettings: "إعدادات المظهر",
        lightMode: "الوضع الفاتح",
        darkMode: "الوضع الداكن",
        adminPasswordSettings: "إدارة كلمات مرور المشاريع",
        manageProjectPasswords: "إدارة كلمات مرور المشاريع",
        managePasswordsDescription: "تعيين أو تحديث كلمات المرور لجميع المشاريع المحفوظة",
        managePasswordsButton: "إدارة كلمات المرور",
        projectPasswordManagementTitle: "إدارة كلمات مرور المشاريع",
        currentPassword: "كلمة المرور الحالية",
        updatePassword: "تحديث كلمة المرور",
        updateAllPasswords: "تحديث جميع كلمات المرور",
        setGlobalPassword: "تعيين كلمة مرور موحدة",
        setGlobalPasswordDescription: "تعيين نفس كلمة المرور لجميع المشاريع",
        globalPasswordPlaceholder: "أدخل كلمة المرور الموحدة لجميع المشاريع",
        passwordUpdatedSuccess: "تم تحديث كلمة المرور بنجاح!",
        allPasswordsUpdatedSuccess: "تم تحديث جميع كلمات مرور المشاريع بنجاح!",
        passwordUpdateError: "خطأ في تحديث كلمة المرور. يرجى المحاولة مرة أخرى.",
        needHelp: "تحتاج مساعدة؟",
        whatsappSupport: "تواصل مع الدعم عبر واتساب",
        whatsappSupportDescription: "إذا لم تتمكن من إعادة تعيين كلمة المرور، تواصل مع فريق الدعم عبر واتساب للحصول على المساعدة.",
        contactSupport: "تواصل مع الدعم",
        reportIncidentTitle: "الإبلاغ عن حادث سيارة",
        incidentInfo: "معلومات الحادث",
        selectVehicle: "اختر السيارة",
        incidentType: "نوع الحادث",
        accident: "حادث",
        notWorking: "عطل",
        incidentDate: "تاريخ الحادث",
        description: "الوصف",
        submitReport: "إرسال البلاغ",
        reportSuccess: "تم إرسال بلاغ الحادث بنجاح!",
        status_Active: "نشط",
        status_Accident: "حادث",
        status_Not_Working: "عطل",
        reportsTitle: "تقارير الحوادث",
        thVehicle: "السيارة",
        thIncidentType: "نوع الحادث",
        thIncidentDate: "التاريخ",
        thDescription: "الوصف",
        noIncidentsFound: "لم يتم الإبلاغ عن أي حوادث حتى الآن.",
        import: "استيراد",
        importVehicles: "استيراد السيارات",
        importDrivers: "استيراد السائقين",
        importSuccess: "تم استيراد البيانات بنجاح!",
        importError: "فشل استيراد البيانات. يرجى التحقق من تنسيق الملف ومحتواه.",
        thAssignedVehicleDoorNumber: "رقم باب السيارة المعينة",

        // Transfers
        transferVehicleTitle: "نقل سيارة",
        transferInfo: "معلومات النقل",
        currentProject: "المشروع الحالي",
        transferTo: "نقل إلى",
        transferDate: "تاريخ ووقت النقل",
        selectProject: "اختر مشروع الوجهة...",
        confirmTransfer: "تأكيد النقل",
        transferSuccess: "تم نقل السيارة بنجاح!",
        transferError: "خطأ في نقل السيارة.",
        transferHistory: "سجل النقل",
        noTransfersFound: "لا يوجد سجل نقل.",
        thFromProject: "من مشروع",
        thToProject: "إلى مشروع",
        status_Transferred: "تم النقل",
        status_Returned: "تم الإرجاع",
        notifyAdmin: "إبلاغ المسؤول",
        notifyAdminSent: "إبلاغ بالإرسال",
        notifyAdminReturned: "إبلاغ بالعودة",
        notified: "تم الإبلاغ",
        notificationSent: "تم إبلاغ المسؤول.",
        deleteTransferTitle: "حذف النقل",
        deleteTransferMessage: "هل أنت متأكد أنك تريد حذف سجل النقل هذا؟ لا يمكن التراجع عن هذا الإجراء.",

        // Admin
        adminDashboard: "لوحة التحكم",
        totalProjects: "إجمالي المشاريع",
        allProjectsReport: "تقرير جميع المشاريع",
        allIncidentsReport: "تقرير جميع الحوادث",
        allVehiclesReport: "تقرير جميع السيارات",
        viewProjectDashboard: "عرض لوحة التحكم",
        thProjectName: "اسم المشروع",
        thProjectManager: "المدير",
        thProjectId: "معرف المشروع",
        totalIncidents: "إجمالي الحوادث",
        globalVehicleSearch: "بحث شامل عن السيارات",
        searchByDoorNumberAdmin: "ابحث برقم الباب...",
        globalDriverSearch: "بحث شامل عن السائقين",
        searchByIqama: "ابحث برقم الإقامة...",
        vehicleFoundIn: "تم العثور على السيارة في مشروع",
        driverFoundIn: "تم العثور على السائق في مشروع",
        driverNotFound: "لم يتم العثور على سائق برقم الإقامة هذا.",
        vehiclesByServiceType: "السيارات حسب سيارة الخدمة",
        totalVehiclesByProject: "إجمالي السيارات حسب المشروع",
        totalVehiclesByProjectAndType: "إجمالي السيارات حسب المشروع والنوع",
        allProjects: "جميع المشاريع",
        filterByProject: "تصفية حسب المشروع...",
        transferLog: "سجل النقل",
        transferNotifications: "إشعارات النقل",
        dismissNotification: "تجاهل",
        noNewNotifications: "لا توجد إشعارات جديدة.",
        clearAll: "مسح الكل",
        clearAllNotificationsTitle: "مسح جميع الإشعارات",
        clearAllNotificationsMessage: "هل أنت متأكد أنك تريد حذف جميع الإشعارات بشكل دائم؟",
        adminReports: "التقارير",
        adminTransferLog: "التحويلات",
        adminAllProjects: "المشاريع",
        adminAllIncidents: "الحوادث",
        adminAllVehicles: "السيارات",

        // Man Power
        menPower: "القوى العاملة",
        addSupervisor: "إضافة مشرف",
        supervisorOverview: "نظرة عامة على المشرفين",
        addSupervisorTitle: "إضافة مشرف جديد",
        supervisorInfo: "معلومات المشرف",
        supervisorName: "اسم المشرف",
        areaLocation: "المنطقة / الموقع",
        supervisorIqama: "رقم إقامة المشرف",
        supervisorMobile: "رقم جوال المشرف",
        foremenInfo: "معلومات المراقبين",
        addForeman: "إضافة مراقب",
        foremanName: "اسم المراقب",
        totalAssignedLabour: "إجمالي العمالة المخصصة",
        saveSupervisor: "حفظ المشرف",
        supervisorSaveSuccess: "تم حفظ المشرف والمراقبين بنجاح!",
        supervisorUpdateSuccess: "تم تحديث المشرف بنجاح!",
        supervisorOverviewTitle: "نظرة عامة على القوى العاملة",
        campLabour: "عامل معسكر",
        crewman: "عامل الضاغط",
        totalLabour: "إجمالي العمالة",
        manpowerBySupervisor: "القوى العاملة حسب المشرف",
        workers: "عمال",
        noSupervisorsFound: "لم يتم إضافة أي مشرفين بعد.",
        totalSupervisors: "إجمالي المشرفين",
        totalForemen: "إجمالي المراقبين",
        projectLevelLabour: "عمالة على مستوى المشروع",
        vehicleFleet: "أسطول السيارات",
        manPowerStatistics: "إحصائيات القوى العاملة",
        editSupervisorTitle: "تعديل المشرف",
        deleteSupervisorTitle: "حذف المشرف",
        deleteSupervisorMessage: "هل أنت متأكد أنك تريد حذف هذا المشرف وجميع المراقبين المرتبطين به؟",

        // Project Officers
        projectOfficersHeader: "مسؤولو المشروع",
        addProjectOfficers: "إضافة/تعديل المسؤولين",
        viewProjectOfficers: "عرض تقرير المسؤولين",
        officerRole_Project_Manager: "مدير المشروع",
        officerRole_Assistant_Project_Manager: "مساعد مدير المشروع",
        officerRole_Operation_Manager: "مدير العمليات",
        officerRole_Admin_Manager: "المدير الإداري",
        officerRole_Camp_Boss: "مسؤول السكن",
        officerRole_Fleet_Manager: "مدير الأسطول",
        officerRole_Haraka_Supervisor_1: "مشرف الحركة 1",
        officerRole_Haraka_Supervisor_2: "مشرف الحركة 2",
        officerRole: "دور المسؤول",
        officerName: "الاسم",
        officerIqama: "رقم الإقامة",
        officerMobile: "رقم الجوال",
        updateOfficers: "تحديث المسؤولين",
        officersUpdateSuccess: "تم تحديث مسؤولي المشروع بنجاح!",
        exportOfficers: "تصدير تقرير المسؤولين",
        noOfficersFound: "لم يتم إضافة أي مسؤولي مشروع بعد.",
        projectOfficersReport: "تقرير مسؤولي المشروع",
        addOfficer: "إضافة مسؤول",
        deleteOfficerTitle: "حذف المسؤول",
        deleteOfficerMessage: "هل أنت متأكد أنك تريد حذف هذا المسؤول؟",

        // Project Names (for programmatic lookup)
        projectName_Riyadh_Site_Project: "مشروع موقع الرياض",
        projectName_Jeddah_Expansion: "توسعة جدة",
    }
};