import type { NavLink, Page, ProjectOfficerRole, Labour, Vehicle, Driver, Incident, Transfer } from './types';

export const NAV_LINKS: NavLink[] = [
  { href: "#", icon: "fas fa-home", labelKey: "dashboard" },
  
  // ADMIN ONLY - Most important items first
  { type: "header", href: "#", icon: "fas fa-shield-alt", labelKey: "adminReports", adminOnly: true },
  { href: "#", icon: "fas fa-car-side", labelKey: "adminAllVehicles", adminOnly: true },
  { href: "#", icon: "fas fa-id-card", labelKey: "adminAllDrivers", adminOnly: true },
  { href: "#", icon: "fas fa-list-alt", labelKey: "adminAllProjects", adminOnly: true },
  { href: "#", icon: "fas fa-users-cog", labelKey: "adminAllMenpowerReport", adminOnly: true },
  { href: "#", icon: "fas fa-exclamation-triangle", labelKey: "adminAllIncidents", adminOnly: true },
  { href: "#", icon: "fas fa-route", labelKey: "adminTransferLog", adminOnly: true },

  // USER LINKS
  { type: "header", href: "#", icon: "fas fa-users", labelKey: "menpower" },
  { href: "#", icon: "fas fa-user-plus", labelKey: "addMenpower" },
  { href: "#", icon: "fas fa-tasks", labelKey: "menpowerOverview" },
  { href: "#", icon: "fas fa-user-check", labelKey: "manpowerAssign" },
  { type: "header", href: "#", icon: "fas fa-car", labelKey: "vehicleFleet" },
  { href: "#", icon: "fas fa-car", labelKey: "addVehicle" },
  { href: "#", icon: "fas fa-list", labelKey: "viewVehicles" },
  { href: "#/add-driver", icon: "fas fa-user-plus", labelKey: "addDriver" },
  { href: "#/view-drivers", icon: "fas fa-users", labelKey: "viewDrivers" },
  { href: "#", icon: "fas fa-exchange-alt", labelKey: "transferVehicle"},
  { href: "#", icon: "fas fa-car-crash", labelKey: "reportIncident" },
  { href: "#", icon: "fas fa-history", labelKey: "vehicleHistory" },
  { href: "#", icon: "fas fa-cog", labelKey: "settings" },
  { href: "#", icon: "fas fa-sign-out-alt", labelKey: "logout" },
];

export const PROJECT_OFFICER_ROLES: ProjectOfficerRole[] = [
    'Project Manager',
    'Assistant Project Manager',
    'Operation Manager',
    'Admin Manager',
    'Camp Boss',
    'Fleet Manager',
    'Haraka Supervisor 1',
    'Haraka Supervisor 2',
    'Other'
];

export const SERVICE_TYPES = {
    en: [
        'Bulk Waste Collection',
        'Emergency CWC Service',
        'Recyclable Waste',
        'Litter Picking',
        'Street Sweeping',
        'Container Maintenance',
        'Container Cleaning',
        'CWC (REL) Service',
        'Container Washing Truck',
        'Container Distribution Truck',
        'Roads & Sidewalks Washing Vehicle',
        'Mechanical Sweeper',
        'Pavement Sweeping Machine',
        'Sanitation Machine',
        'Small Sweeper',
        'Trailer Sweeper',
        'Litter Suction Machine',
        'Wheel Loader',
        'Dump Truck',
        'Roll On/Off - Lugger',
        'Solid Waste Chopper/Shredder Machine',
        'Trees & Wood Chopper/Shredder Machine',
        'Other'
    ],
    ar: [
        'جمع النفايات الكبيرة',
        'خدمة الطوارئ CWC',
        'النفايات القابلة لإعادة التدوير',
        'جمع النفايات المتناثرة',
        'كنس الشوارع',
        'صيانة الحاويات',
        'غسيل الحاويات',
        'خدمة CWC (REL)',
        'شاحنة غسيل الحاويات',
        'شاحنة توزيع الحاويات',
        'مركبة غسيل الطرق والأرصفة',
        'مكنسة ميكانيكية',
        'آلة كنس الأرصفة',
        'آلة التعقيم',
        'مكنسة صغيرة',
        'مكنسة مقطورة',
        'آلة شفط النفايات',
        'جرافة (لودر بعجلات)',
        'شاحنة قلّاب',
        'شاحنة رول أون/أوف (لوغر)',
        'آلة فرم النفايات الصلبة',
        'آلة تقطيع وفرم الأشجار والأخشاب',
        'أخرى'
    ]
};

export const ARABIC_SERVICE_TYPES_FOR_EXPORT = [
    'ضاغط كبير',
    'ضاغط صغير',
    'قلاب 3 م',
    'قلاب 6 م',
    'قلاب 16 م',
    'قلاب 24 م',
    'راس تريلا',
    'كانسة الية كبير',
    'بيك اب غمارة',
    'بيك اب غمارتين',
    'تنكر غسيل ارصفة',
    'تنكر غسيل حاويات',
    'سيارة توزيع حاويات',
    'هوك ليفت',
    'ضاغط تدوير',
    'مكبس 60 م',
    'مكينة شفط الالتقاط محموله علي سيارة',
    'كرين',
    'قلاب 5 طن',
    'شيول كبير',
    'شيول وسط',
    'بوبكات',
    'ماكينة فرم اخشاب',
    'كانسة الية حجم صغير',
    'مكينة فرم المخلفات الصلبة',
    'معدة كنس ارصفه',
    'مكينة شفط للالتقاط',
    'معدة تطهير',
    'رافعه شوكيه',
    'بيك اب غمارة بدون صندوق',
    'وايت شفط',
    'مكنسة مجرورة',
    'فورتشنر',
    'باجيرو',
    'باص',
    'كريتا'
];

export const INCIDENT_TYPES = [
    { value: 'Accident', labelKey: 'accident' },
    { value: 'Electrical Breakdown', labelKey: 'electricalBreakdown' },
    { value: 'Preventive Maintenance', labelKey: 'preventiveMaintenance' },
    { value: 'Mechanical Breakdown', labelKey: 'mechanicalBreakdown' },
    { value: 'Suspension Breakdown', labelKey: 'suspensionBreakdown' },
    { value: 'Hydraulic Breakdown', labelKey: 'hydraulicBreakdown' },
    { value: 'Body & Paint Breakdown', labelKey: 'bodyPaintBreakdown' },
    { value: 'Tire Breakdown', labelKey: 'tireBreakdown' },
    { value: 'AC Breakdown', labelKey: 'acBreakdown' },
    { value: 'Other', labelKey: 'other' },
];

export const AFFECTED_PARTS_MAP: Record<string, Record<string, string[]>> = {
    en: {
        'Electrical Breakdown': ['Battery', 'Alternator', 'Starter Motor', 'Wiring', 'Lights', 'Other'],
        'Preventive Maintenance': ['Oil Change', 'Filter Replacement', 'Fluid Check', 'Brake Inspection', 'Other'],
        'Mechanical Breakdown': ['Engine', 'Transmission', 'Clutch', 'Radiator', 'Exhaust', 'Other'],
        'Suspension Breakdown': ['Shock Absorbers', 'Springs', 'Axle', 'Control Arms', 'Other'],
        'Hydraulic Breakdown': ['Hydraulic Pump', 'Hoses', 'Cylinders', 'Valves', 'Other'],
        'Body & Paint Breakdown': ['Dents', 'Scratches', 'Rust Repair', 'Painting', 'Other'],
        'Tire Breakdown': ['Flat Tire', 'Tire Replacement', 'Wheel Alignment', 'Other'],
        'AC Breakdown': ['Compressor', 'Condenser', 'Evaporator', 'Refrigerant Leak', 'Other'],
    },
    ar: {
        'Electrical Breakdown': ['بطارية', 'دينامو', 'محرك بدء التشغيل', 'أسلاك', 'أضواء', 'أخرى'],
        'Preventive Maintenance': ['تغيير زيت', 'تغيير فلتر', 'فحص السوائل', 'فحص الفرامل', 'أخرى'],
        'Mechanical Breakdown': ['محرك', 'ناقل حركة', 'كلتش', 'ردياتير', 'عادم', 'أخرى'],
        'Suspension Breakdown': ['ممتص صدمات', 'يايات', 'محور', 'أذرعة تحكم', 'أخرى'],
        'Hydraulic Breakdown': ['مضخة هيدروليكية', 'خراطيم', 'أسطوانات', 'صمامات', 'أخرى'],
        'Body & Paint Breakdown': ['صدمات', 'خدوش', 'إصلاح صدأ', 'دهان', 'أخرى'],
        'Tire Breakdown': ['إطار مثقوب', 'تغيير إطار', 'ميزان عجلات', 'أخرى'],
        'AC Breakdown': ['كمبروسر', 'مكثف', 'مبخر', 'تسريب فريون', 'أخرى'],
    }
};



export const CHART_COLORS = [
    '#d946ef', '#db2777', '#dc2626', '#ea580c', '#f59e0b', '#ca8a04', 
    '#65a30d', '#16a34a', '#059669', '#0d9488', '#0891b2', '#0284c7', 
    '#2563eb', '#4f46e5', '#7c3aed', '#c026d3', '#be185d', '#b91c1c'
];

// Mock data removed - Using real Firebase data only


export const TRANSLATIONS = {
    en: {
        // Auth
        loginTitle: "Sign In",
        signUpTitle: "Create Account",
        email: "Email Address",
        password: "Password",
        confirmPassword: "Confirm Password",
        projectName: "Project Name",
        projectManagerName: "Project Manager Name",
        projectId: "Project ID",
        operatorName: "Data Entry Operator Name",
        createAccount: "Create Account",
        signIn: "Sign In",
        dontHaveAccount: "Don't have an account?",
        signUpHere: "Sign Up",
        alreadyHaveAccount: "Already have an account?",
        signInHere: "Sign In",
        accountCreatedSuccess: "Account created successfully! Please sign in.",
        invalidCredentials: "Invalid email or password.",
        emailInvalid: "Please enter a valid email address.",
        passwordInvalid: "Password must be at least 8 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        welcome: "Welcome",
        forgotPassword: "Forgot Password?",
        forgotPasswordTitle: "Reset Password",
        forgotPasswordInstructions: "Enter your email address and we'll send you a link to reset your password.",
        sendResetLink: "Send Reset Link",
        resetEmailSent: "If an account with that email exists, a password reset link has been sent.",
        backToLogin: "Back to Login",
        adminLogin: "Admin Login",
        adminLoginHint: "Please enter the admin email and password.",
        tooManyRequests: "Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.",
        genericAuthError: "An unexpected error occurred. Please try again.",
        
        // App
        appName: "Environmental Services Zahran Fleet",
        dashboard: "Dashboard",
        addVehicle: "Add Vehicle",
        viewVehicles: "View Vehicles",
        viewVehicleDetails: "Vehicle Details",
        addDriver: "Add Driver",
        viewDrivers: "View Drivers",
        transferVehicle: "Transfer Vehicle",
        reportIncident: "Report Incident",
        vehicleHistory: "Vehicle History",
        settings: "Settings",
        logout: "Logout",
        addDriverTitle: "Add New Driver",
        driverInfo: "Driver Information",
        driverName: "Driver Name",
        nationality: "Nationality",
        driverIqama: "Driver's Iqama Number",
        driverIdNumber: "Driver ID Number",
        driverMobile: "Driver's Mobile Number",
        assignVehicle: "Assign Vehicle",
        assignedVehicle: "Assigned Vehicle (Door Number)",
        selectVehicleOptional: "Select a vehicle (Optional)",
        selectDriverOptional: "Select a driver (Optional)",
        searchVehicleHint: "Type door number, plate number, or chassis number to search.",
        cancel: "Cancel",
        saveDriver: "Save Driver",
        saveSuccess: "Driver saved successfully!",
        saveError: "Error saving. Please check the form for errors.",
        requiredField: "This field is required.",
        vehicleAlreadyAssigned: "This vehicle is already assigned to another driver.",
        doorNumberExists: "This door number is already registered in the system.",
        iqamaInvalid: "Please enter a valid 10-digit Iqama number.",
        mobileInvalid: "Please enter a valid Saudi mobile number starting with 5.",
        noVehiclesFound: "No vehicles found.",
        vehicleSearchPlaceholder: "Search vehicle...",
        viewDriversTitle: "View Drivers",
        searchByNameOrIqama: "Search by name, Iqama, or ID number...",
        noDriversFound: "No drivers found.",
        thDriverName: "Driver Name",
        thDriver: "Driver",
        thDriverIdNumber: "Driver ID Number",
        thIqama: "Iqama",
        thMobile: "Mobile",
        thAssignedVehicle: "Assigned Vehicle",
        unassigned: "Unassigned",
        actions: "Actions",
        addVehicleTitle: "Add New Vehicle / Equipment",
        vehicleInfo: "Vehicle / Equipment Information",
        doorNumber: "Door Number",
        plateNumber: "Plate Number",
        chassisNumber: "Chassis Number",
        saveVehicle: "Save Vehicle",
        saveVehicleSuccess: "Vehicle saved successfully!",
        make: "Make / Model",
        manufacturer: "Manufacturer",
        projectSite: "Project Site / Area",
        year: "Year",
        purchaseDate: "Purchase Date",
        tareWeight: "Tare Weight (KG)",
        serviceType: "Service Type",
        otherServiceType: "Other Service Type",
        viewVehiclesTitle: "View Vehicles / Equipment",
        searchByDoorPlateChassis: "Search by Door, Plate, or Chassis...",
        thDoorNumber: "Door #",
        thPlateNumber: "Plate #",
        thChassisNumber: "Chassis #",
        thMake: "Make / Model",
        thManufacturer: "Manufacturer",
        thProjectSite: "Project Site",
        thYear: "Year",
        thPurchaseDate: "Purchase Date",
        thTareWeight: "Tare Weight",
        thServiceType: "Service Type",
        thStatus: "Status",
        totalProjects: "Total Projects",
        totalVehicles: "Total Vehicles",
        totalDrivers: "Total Drivers",
        unassignedVehicles: "Unassigned Vehicles",
        vehiclesInWorkshop: "Vehicles in Workshop",
        vehiclesByArea: "Vehicles by Project Site",
        vehiclesByServiceType: "Vehicles by Service Type",
        driversByNationality: "Drivers by Nationality",
        addedNewVehicle: "Added new vehicle",
        addedNewDriver: "Added new driver",
        noRecentActivity: "No recent activity to display.",
        recentActivityPageTitle: "Recent Activity Log",
        activityLogWillBeCleared: "Note: This log is for the current session and will be cleared when you navigate away.",
        event_CREATED: "Created",
        event_UPDATED: "Updated",
        event_DELETED: "Deleted",
        event_ASSIGNED: "Assigned",
        event_UNASSIGNED: "Unassigned",
        event_TRANSFERRED: "Transferred",
        vehicleDetailsTitle: "Vehicle / Equipment Details",
        assignedDriver: "Assigned Driver",
        searchByDoorNumber: "Enter Door Number...",
        search: "Search",
        vehicleDetailsSearchPrompt: "Search for a vehicle by its door number to see details.",
        vehicleNotFound: "Vehicle with this door number not found.",
        noVehicleSelected: "Please select a vehicle from the 'View Vehicles' list to see its details.",
        viewDetails: "View Details",
        editVehicleTitle: "Edit Vehicle / Equipment",
        saveChanges: "Save Changes",
        delete: "Delete",
        deleteVehicleTitle: "Delete Vehicle",
        deleteVehicleMessage: "Are you sure you want to delete this vehicle? This action cannot be undone.",
        confirmDelete: "Yes, Delete",
        editDriverTitle: "Edit Driver",
        deleteDriverTitle: "Delete Driver",
        deleteDriverMessage: "Are you sure you want to delete this driver?",
        deleteSelected: "Delete Selected ({count})",
        deleteSelectedItemsTitle: "Delete Selected Items",
        deleteSelectedItemsMessage: "Are you sure you want to delete the {count} selected items? This action cannot be undone.",
        event: "Event",
        timestamp: "Timestamp",
        details: "Details",
        settingsTitle: "Settings",
        languageSettings: "Language Settings",
        chooseLanguage: "Choose your preferred language.",
        english: "English",
        arabic: "Arabic",
        themeSettings: "Theme Settings",
        lightMode: "Light",
        darkMode: "Dark",
        reportIncidentTitle: "Report Vehicle Incident",
        incidentInfo: "Incident Information",
        selectVehicle: "Select Vehicle",
        incidentType: "Incident Type",
        accident: "Accident",
        incidentDate: "Incident Date",
        description: "Description",
        submitReport: "Submit Report",
        reportSuccess: "Incident report submitted successfully!",
        status_Active: "Active",
        status_Accident: "Accident",
        status_Breakdown: "Breakdown",
        reportsTitle: "Incident Reports",
        thVehicle: "Vehicle",
        thIncidentType: "Incident Type",
        thIncidentDate: "Date",
        thDescription: "Description",
        noIncidentsFound: "No incidents reported yet.",
        import: "Import",
        importVehicles: "Import Vehicles",
        importDrivers: "Import Drivers",
        importSuccess: "Data imported successfully!",
        importing: "Importing",
        importError: "Failed to import data. Please check the file format and content.",
        thAssignedVehicleDoorNumber: "Assigned Vehicle Door Number",
        
        // New Incident Types
        electricalBreakdown: "Electrical Breakdown",
        preventiveMaintenance: "Preventive Maintenance",
        mechanicalBreakdown: "Mechanical Breakdown",
        suspensionBreakdown: "Suspension Breakdown",
        hydraulicBreakdown: "Hydraulic Breakdown",
        bodyPaintBreakdown: "Body & Paint Breakdown",
        tireBreakdown: "Tire Breakdown",
        acBreakdown: "AC Breakdown",
        other: "Other",
        affectedPart: "Affected Part / Item",
        specifyIncidentType: "Please specify incident type",
        specifyAffectedPart: "Please specify affected part",

        // Transfers
        transferVehicleTitle: "Transfer Vehicle",
        transferInfo: "Transfer Information",
        currentProject: "Current Project",
        transferTo: "Transfer To",
        transferDate: "Transfer Date & Time",
        selectProject: "Select a destination project...",
        confirmTransfer: "Confirm Transfer",
        transferSuccess: "Vehicle transferred successfully!",
        transferError: "Error transferring vehicle.",
        transferHistory: "Transfer History",
        noTransfersFound: "No transfer history found.",
        thFromProject: "From Project",
        thToProject: "To Project",
        status_Transferred: "Transferred",
        status_Returned: "Returned",
        notifyAdmin: "Notify Admin",
        notifyAdminSent: "Notify Sent",
        notifyAdminReturned: "Notify Returned",
        notified: "Notified",
        notificationSent: "Admin has been notified.",
        deleteTransferTitle: "Delete Transfer",
        deleteTransferMessage: "Are you sure you want to delete this transfer record? This action cannot be undone.",
        returnVehicle: "Return Vehicle",
        returnSuccess: "Vehicle returned successfully!",
        returnError: "Error returning vehicle.",

        // Admin
        adminDashboard: "Admin Dashboard",
        allProjectsReport: "Projects",
        allIncidentsReport: "Incidents",
        allVehiclesReport: "Vehicles",
        viewProjectDashboard: "View Dashboard",
        thProjectName: "Project Name",
        thProjectManager: "Manager",
        thProjectId: "Project ID",
        totalIncidents: "Total Incidents",
        globalVehicleSearch: "Global Vehicle Search",
        searchByDoorNumberAdmin: "Search by Door Number...",
        globalDriverSearch: "Global Driver Search",
        searchByIqama: "Search by Iqama Number...",
        globalSearchPlaceholder: "Search Vehicle (Door/Plate) or Person (Iqama)...",
        vehicleFoundIn: "Vehicle Found in Project",
        driverFoundIn: "Driver Found in Project",
        personFoundIn: "Person Found in Project",
        driverNotFound: "Driver with this Iqama number not found.",
        searchNotFound: "No vehicle or person found with that identifier.",
        totalVehiclesByProject: "Total Vehicles by Project",
        allProjects: "All Projects",
        filterByProject: "Filter by Project...",
        transferLog: "Transfer Log",
        transferNotifications: "Transfer Notifications",
        dismissNotification: "Dismiss",
        noNewNotifications: "No new notifications.",
        clearAll: "Clear All",
        clearAllNotificationsTitle: "Clear All Notifications",
        clearAllNotificationsMessage: "Are you sure you want to permanently delete all notifications?",
        adminReports: "Admin Reports",
        adminTransferLog: "Transfer Log",
        adminAllProjects: "Projects",
        adminAllMenpower: "Manpower",
        adminAllMenpowerReport: "Manpower",
        viewMenpower: "Manpower",
        adminAllIncidents: "Incidents",
        adminAllVehicles: "Vehicles",
        adminAllDrivers: "Drivers",

        // Menpower
        menpower: "Menpower",
        supervisors: "Supervisors",
        addMenpower: "Add Menpower",
        dynamicJson: "Dynamic JSON Structure",
        menpowerOverview: "Menpower Overview",
        manpowerAssign: "Assign Manpower",
        addMenpowerTitle: "Add Menpower",
        downloadTemplate: "Download Template",
        downloadForemenTemplate: "Download Foremen Template", 
        downloadLabourTemplate: "Download Labour Template",
        templateDownloadSuccess: "Template downloaded successfully",
        supervisorInfo: "Supervisor Information",
        supervisorName: "Supervisor",
        supervisorEmpId: "Employee ID",
        areaLocation: "Area / Location",
        supervisorIqama: "Supervisor's Iqama Number",
        supervisorMobile: "Supervisor's Mobile Number",
        foremenInfo: "Foremen Information",
        addForeman: "Add Foreman",
        foremanName: "Foreman Name",
        foremanIqama: "Foreman's Iqama",
        foremanEmpId: "Foreman's Employee ID",
        saveSupervisor: "Save Supervisor",
        supervisorSaveSuccess: "Supervisor and foremen saved successfully!",
        supervisorUpdateSuccess: "Supervisor updated successfully!",
        menpowerOverviewTitle: "Manpower Summary",
        menpowerBySupervisor: "Menpower by Supervisor",
        campLabour: "Camp Labour",
        crewman: "Crewman",
        totalLabour: "Total Labour",
        totalLabours: "Total Labours",
        totalWorkforce: "Total Workforce",
        totalMenpower: "Total Menpower",
        total: "Total",
        labour: "Labour",
        labourName: "Labour Name",
        labourIqama: "Labour's Iqama",
        labourEmpId: "Labour's Employee ID",
        addLabour: "Add Labour",
        noSupervisorsFound: "No supervisors have been added yet.",
        totalSupervisors: "Total Supervisors",
        totalForemen: "Total Foremen",
        projectLevelLabour: "Project Level Labour",
        vehicleFleet: "Vehicle Fleet",
        menpowerStatistics: "Menpower Statistics",
        editSupervisorTitle: "Edit Supervisor",
        deleteSupervisorTitle: "Delete Supervisor",
        deleteSupervisorMessage: "Are you sure you want to delete this supervisor and all associated foremen?",
        resourceClassification: "Resource Classification",
        assignToSupervisor: "Assign to Supervisor",
        assignToForeman: "Assign to Foreman",
        selectSupervisor: "Select Supervisor...",
        selectForeman: "Select Foreman...",
        personalInfo: "Personal Information",
        saveEntry: "Save Entry",
        entrySaveSuccess: "Menpower entry saved successfully!",
        entryType: "Entry Type",
        selectEntryType: "Select entry type...",
        entryDetails: "Entry Details",
        foreman: "Foreman",
        personName: "Name",
        employeeId: "Employee ID",
        iqamaNumber: "Iqama Number",
        selectSupervisorPrompt: "First, select a supervisor...",
        projectOfficer: "Project Officer",
        totalOfficers: "Total Officers",
        viewSupervisors: "View Supervisors",
        supervisorDetails: "Supervisor Details",
        overview: "Overview",
        foremen: "Foremen",
        labours: "Labours",
        vehicles: "Vehicles",
        reports: "Reports",
        selectSupervisorToView: "Select a supervisor from the list to view their details.",
        featureComingSoon: "Feature coming soon.",
        labourDetails: "Labour Details",
        selectForemanPrompt: "Please select a foreman to view their assigned labourers.",
        vehiclesLabel: "Vehicles",
        showDetails: "Show Details",
        hideDetails: "Hide Details",
        searchByServiceType: "Search by Service Type...",
        allSites: "All Sites",
        editServiceTypeTitle: "Edit Service Type",
        newServiceType: "New Service Type",
        updateServiceType: "Update Service Type",
        serviceTypeUpdateSuccess: "Service types updated successfully!",
        allServiceTypes: "All Service Types",
        
        // Project Officers
        projectOfficersHeader: "Project Officers",
        addProjectOfficers: "Add/Edit Officers",
        viewProjectOfficers: "View Project Officers",
        officerRole_Project_Manager: "Project Manager",
        officerRole_Assistant_Project_Manager: "Assistant Project Manager",
        officerRole_Operation_Manager: "Operation Manager",
        officerRole_Admin_Manager: "Admin Manager",
        officerRole_Camp_Boss: "Camp Boss",
        officerRole_Fleet_Manager: "Fleet Manager",
        officerRole_Haraka_Supervisor_1: "Haraka Supervisor 1",
        officerRole_Haraka_Supervisor_2: "Haraka Supervisor 2",
        officerRole_Other: "Other",
        officerRole: "Officer Role",
        officerName: "Name",
        officerId: "Officer ID Number",
        officerIqama: "Iqama Number",
        officerMobile: "Mobile Number",
        updateOfficers: "Update Officers",
        officersUpdateSuccess: "Project officers updated successfully!",
        exportOfficers: "Export Officers Report",
        exportForemen: "Export All Foremen",
        exportLabour: "Export All Labour",
        noOfficersFound: "No project officers have been added yet.",
        projectOfficersReport: "Project Officers Report",
        addOfficer: "Add Officer",
        deleteOfficerTitle: "Delete Officer",
        deleteOfficerMessage: "Are you sure you want to delete this officer?",
        editOfficerTitle: "Edit Project Officer",
        exportAllMenpower: "Export All Menpower",
        viewCrewmen: "View Crewmen",
        viewCampLabours: "View Camp Labours",
        noCrewmenFound: "No crewmen found.",
        noCampLaboursFound: "No camp labours found.",
        editLabourTitle: "Edit Labour",
        deleteLabourTitle: "Delete Labour",
        deleteLabourMessage: "Are you sure you want to delete this labourer?",
        importProjectOfficers: "Import Project Officers",
        importCrewmen: "Import Crewmen",
        importCampLabours: "Import Camp Labours",
        importSupervisors: "Import Supervisors",
        exportSupervisors: "Export Supervisors Report",
        assignedAreaName: "Assigned Area Name",
        totalForman: "Total Foremen",
        searchBySupervisorNameOrIqama: "Search by Name or Iqama...",
        noSupervisorsFoundSearch: "No supervisors have been added yet.",
        deleteSupervisorsTitle: "Delete Supervisors",
        deleteSupervisorsMessage: "Are you sure you want to delete the selected supervisors and all their associated foremen?",

        // Manpower Summary Modal
        manpowerSummaryTitle: "Manpower Summary",
        selectSupervisorFirst: "First select a supervisor to view foremen",
        selectForemanToViewLabour: "Select a foreman to view their labour",
        noForemenUnderSupervisor: "No foremen found under this supervisor",
        noLabourUnderForeman: "No labour found under this foreman",
        viewManpowerSummary: "View Manpower Summary",

        // New Vehicle History Page
        vehicleHistoryTitle: "Vehicle History Log",
        reportsPageInfo: "This page shows vehicles that need attention or have been recently repaired",
        bulkSelect: "Bulk Select",
        selectAll: "Select All",
        searchByDoorNumberVH: "Search by Door Number",
        dateFrom: "From Date",
        dateTo: "To Date",
        filterByStatusVH: "Filter by Status",
        allStatusesVH: "All Statuses",
        activeVH: "Active",
        underIncidentVH: "Under Incident",
        recentlyRepairedVH: "Recently Repaired",
        clearFilters: "Clear Filters",
        problematicVehiclesOverview: "Problematic Vehicles Overview",
        noProblematicVehicles: "All vehicles are working normally - No vehicles require attention",
        latestIncident: "Latest Incident:",
        totalIncidentsLabel: "Total Incidents",
        markAsRepaired: "Mark as Repaired",
        historyLog: "History Log",
        events: "events",
        noHistoryFound: "No history events found for the selected criteria.",
        createdDate: "Created Date:",
        incidentTypeVH: "Incident Type:",
        reasonDescriptionVH: "Reason / Description:",
        repairDate: "Repair Date",
        repairedByVH: "Repaired By:",
        repairDetails: "Repair Details",
        confirmDeleteHistory: "Confirm Complete History Deletion",
        deleteHistoryWarning: "Warning: This action cannot be undone.",
        deleteHistoryIncidents: "All incidents for selected vehicles",
        deleteHistoryRepairs: "All repair history records",
        deleteHistoryTransfers: "All transfer records",
        deletePermanently: "Delete Completely",
        dismissActiveIncidentTitle: "Dismiss Incident",
        dismissActiveIncidentMessage: "Are you sure you want to dismiss this incident? The vehicle will be marked as 'Active' and this incident record will be removed.",
        dismissHistoryTitle: "Dismiss History",
        dismissHistoryMessage: "Are you sure you want to dismiss the latest repair record? This will remove the repair log and its associated incident.",
        deleteSelectedHistory: "Delete Selected ({count})",
        deleteSelectedHistoryTitle: "Delete History for Selected Vehicles",
        deleteSelectedHistoryMessage: "Are you sure you want to permanently delete all history records (incidents, repairs, transfers) for the {count} selected vehicles? This action cannot be undone.",
        dismissSelectedHistoryTitle: "Delete Selected History",
        dismissSelectedHistoryMessage: "Are you sure you want to delete the {count} selected history records? This will remove the repair logs and their associated incidents.",

        // Mark As Repaired Modal
        markVehicleActiveTitle: "Mark Vehicle as Active",
        vehicleInformation: "Vehicle Information",
        currentStatus: "Current Status:",
        repairedBy: "Repaired By",
        repairedByPlaceholder: "Name of person/company who repaired",
        repairNotes: "Repair Notes (Optional)",
        repairNotesPlaceholder: "Additional details about the repair completed...",
        confirmRepairWarning: "By confirming the repair, this vehicle will be removed from the problematic vehicles list and will become active again.",
        confirmRepair: "Confirm Repair",
        confirmed: "Confirmed!",
        confirming: "Confirming...",
        repairSuccessMessage: "✅ Vehicle repair confirmed successfully! Window will close...",

        // Project Names (for programmatic lookup)
        projectName_Riyadh_Site_Project: "Riyadh Site Project",
        projectName_Jeddah_Expansion: "Jeddah Expansion",
    },
    ar: {
        // Auth
        loginTitle: "تسجيل الدخول",
        signUpTitle: "إنشاء حساب",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        confirmPassword: "تأكيد كلمة المرور",
        projectName: "اسم المشروع",
        projectManagerName: "اسم مدير المشروع",
        projectId: "معرف المشروع",
        operatorName: "اسم مدخل البيانات",
        createAccount: "إنشاء حساب",
        signIn: "تسجيل الدخول",
        dontHaveAccount: "ليس لديك حساب؟",
        signUpHere: "سجل هنا",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        signInHere: "سجل الدخول",
        accountCreatedSuccess: "تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.",
        invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
        emailInvalid: "الرجاء إدخال عنوان بريد إلكتروني صالح.",
        passwordInvalid: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
        passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.",
        welcome: "أهلاً بك",
        forgotPassword: "هل نسيت كلمة المرور؟",
        forgotPasswordTitle: "إعادة تعيين كلمة المرور",
        forgotPasswordInstructions: "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور الخاصة بك.",
        sendResetLink: "إرسال رابط إعادة التعيين",
        resetEmailSent: "إذا كان هناك حساب بهذا البريد الإلكتروني، فقد تم إرسال رابط إعادة تعيين كلمة المرور.",
        backToLogin: "العودة لتسجيل الدخول",
        adminLogin: "دخول المسؤول",
        adminLoginHint: "الرجاء إدخال البريد الإلكتروني وكلمة المرور الخاصة بالمسؤول.",
        tooManyRequests: "تم تعطيل الوصول إلى هذا الحساب مؤقتًا بسبب العديد من محاولات تسجيل الدخول الفاشلة. يمكنك استعادته فورًا عن طريق إعادة تعيين كلمة المرور أو يمكنك المحاولة مرة أخرى لاحقًا.",
        genericAuthError: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",

        // App
        appName: "أسطول زهران للخدمات البيئية",
        dashboard: "لوحة التحكم",
        addVehicle: "إضافة سيارة",
        viewVehicles: "عرض السيارات",
        viewVehicleDetails: "تفاصيل السيارة",
        addDriver: "إضافة سائق",
        viewDrivers: "عرض السائقين",
        transferVehicle: "نقل سيارة",
        reportIncident: "الإبلاغ عن حادث",
        vehicleHistory: "سجل المركبات",
        settings: "الإعدادات",
        logout: "تسجيل خروج",
        addDriverTitle: "إضافة سائق جديد",
        driverInfo: "معلومات السائق",
        driverName: "اسم الشخص",
        nationality: "الجنسية",
        driverIqama: "رقم الإقامة",
        driverIdNumber: "رقم الهوية",
        driverMobile: "رقم الجوال",
        assignVehicle: "تعيين سيارة",
        assignedVehicle: "السيارة المعينة (رقم الباب)",
        selectVehicleOptional: "اختر سيارة (اختياري)",
        selectDriverOptional: "اختر سائق (اختياري)",
        searchVehicleHint: "اكتب رقم الباب أو رقم اللوحة أو رقم الهيكل للبحث.",
        cancel: "إلغاء",
        saveDriver: "حفظ السائق",
        saveSuccess: "تم حفظ السائق بنجاح!",
        saveError: "خطأ في الحفظ. يرجى التحقق من الحقول.",
        requiredField: "هذا الحقل مطلوب.",
        vehicleAlreadyAssigned: "هذه السيارة معينة بالفعل لسائق آخر.",
        doorNumberExists: "رقم الباب هذا مسجل بالفعل في النظام.",
        iqamaInvalid: "الرجاء إدخال رقم إقامة صحيح مكون من 10 أرقام.",
        mobileInvalid: "الرجاء إدخال رقم جوال سعودي صحيح يبدأ بـ 5.",
        noVehiclesFound: "لم يتم العثور على سيارات.",
        vehicleSearchPlaceholder: "ابحث عن سيارة...",
        viewDriversTitle: "عرض السائقين",
        searchByNameOrIqama: "ابحث بالاسم أو رقم الإقامة أو رقم الهوية...",
        noDriversFound: "لم يتم العثور على سائقين.",
        thDriverName: "اسم السائق",
        thDriver: "السائق",
        thDriverIdNumber: "رقم الهوية",
        thIqama: "الإقامة",
        thMobile: "الجوال",
        thAssignedVehicle: "السيارة المعينة",
        unassigned: "غير معين",
        actions: "إجراءات",
        addVehicleTitle: "إضافة سيارة / معدات جديدة",
        vehicleInfo: "معلومات السيارة / المعدات",
        doorNumber: "رقم الباب",
        plateNumber: "رقم اللوحة",
        chassisNumber: "رقم الهيكل",
        saveVehicle: "حفظ السيارة",
        saveVehicleSuccess: "تم حفظ السيارة بنجاح!",
        make: "النوع / الموديل",
        manufacturer: "الشركة المصنعة",
        projectSite: "موقع المشروع / المنطقة",
        year: "سنة الصنع",
        purchaseDate: "تاريخ الشراء",
        tareWeight: "الوزن الفارغ (كجم)",
        serviceType: "سيارة الخدمة",
        otherServiceType: "سيارة خدمة أخرى",
        viewVehiclesTitle: "عرض السيارات / المعدات",
        searchByDoorPlateChassis: "ابحث برقم الباب، اللوحة، أو الهيكل...",
        thDoorNumber: "رقم الباب",
        thPlateNumber: "رقم اللوحة",
        thChassisNumber: "رقم الهيكل",
        thMake: "النوع / الموديل",
        thManufacturer: "الشركة المصنعة",
        thProjectSite: "موقع المشروع",
        thYear: "سنة الصنع",
        thPurchaseDate: "تاريخ الشراء",
        thTareWeight: "الوزن الفارغ",
        thServiceType: "سيارة الخدمة",
        thStatus: "الحالة",
        totalProjects: "إجمالي المشاريع",
        totalVehicles: "إجمالي السيارات",
        totalDrivers: "إجمالي السائقين",
        unassignedVehicles: "سيارات غير معينة",
        vehiclesInWorkshop: "سيارات في الورشة",
        vehiclesByArea: "السيارات حسب موقع المشروع",
        vehiclesByServiceType: "السيارات حسب نوع الخدمة",
        driversByNationality: "السائقون حسب الجنسية",
        addedNewVehicle: "تمت إضافة سيارة جديدة",
        addedNewDriver: "تمت إضافة سائق جديد",
        noRecentActivity: "لا يوجد نشاط أخير لعرضه.",
        recentActivityPageTitle: "سجل الأنشطة الأخير",
        activityLogWillBeCleared: "ملاحظة: هذا السجل للجلسة الحالية وسيتم مسحه عند الانتقال.",
        event_CREATED: "تم الإنشاء",
        event_UPDATED: "تم التحديث",
        event_DELETED: "تم الحذف",
        event_ASSIGNED: "تم التعيين",
        event_UNASSIGNED: "تم إلغاء التعيين",
        event_TRANSFERRED: "تم النقل",
        vehicleDetailsTitle: "تفاصيل السيارة / المعدات",
        assignedDriver: "السائق المعين",
        searchByDoorNumber: "أدخل رقم الباب...",
        search: "بحث",
        vehicleDetailsSearchPrompt: "ابحث عن سيارة برقم بابها لعرض التفاصيل.",
        vehicleNotFound: "لم يتم العثور على سيارة بهذا الرقم.",
        noVehicleSelected: "يرجى اختيار سيارة من قائمة 'عرض السيارات' لعرض تفاصيلها.",
        viewDetails: "عرض التفاصيل",
        editVehicleTitle: "تعديل السيارة / المعدات",
        saveChanges: "حفظ التغييرات",
        delete: "حذف",
        deleteVehicleTitle: "حذف السيارة",
        deleteVehicleMessage: "هل أنت متأكد أنك تريد حذف هذه السيارة؟ لا يمكن التراجع عن هذا الإجراء.",
        confirmDelete: "نعم، احذف",
        editDriverTitle: "تعديل السائق",
        deleteDriverTitle: "حذف السائق",
        deleteDriverMessage: "هل أنت متأكد أنك تريد حذف هذا السائق؟",
        deleteSelected: "حذف المحدد ({count})",
        deleteSelectedItemsTitle: "حذف العناصر المحددة",
        deleteSelectedItemsMessage: "هل أنت متأكد أنك تريد حذف {count} من العناصر المحددة؟ لا يمكن التراجع عن هذا الإجراء.",
        event: "الحدث",
        timestamp: "الوقت",
        details: "التفاصيل",
        settingsTitle: "الإعدادات",
        languageSettings: "إعدادات اللغة",
        chooseLanguage: "اختر لغتك المفضلة.",
        english: "الإنجليزية",
        arabic: "العربية",
        themeSettings: "إعدادات المظهر",
        lightMode: "الوضع الفاتح",
        darkMode: "الوضع الداكن",
        reportIncidentTitle: "الإبلاغ عن حادث سيارة",
        incidentInfo: "معلومات الحادث",
        selectVehicle: "اختر السيارة",
        incidentType: "نوع الحادث",
        accident: "حادث",
        incidentDate: "تاريخ الحادث",
        description: "الوصف",
        submitReport: "إرسال البلاغ",
        reportSuccess: "تم إرسال بلاغ الحادث بنجاح!",
        status_Active: "نشط",
        status_Accident: "حادث",
        status_Breakdown: "عطل",
        reportsTitle: "تقارير الحوادث",
        thVehicle: "السيارة",
        thIncidentType: "نوع الحادث",
        thIncidentDate: "التاريخ",
        thDescription: "الوصف",
        noIncidentsFound: "لم يتم الإبلاغ عن أي حوادث حتى الآن.",
        import: "استيراد",
        importVehicles: "استيراد السيارات",
        importDrivers: "استيراد السائقين",
        importSuccess: "تم استيراد البيانات بنجاح!",
        importing: "جاري الاستيراد",
        importError: "فشل استيراد البيانات. يرجى التحقق من تنسيق الملف ومحتواه.",
        thAssignedVehicleDoorNumber: "رقم باب السيارة المعينة",

        // New Incident Types
        electricalBreakdown: "عطل كهربائي",
        preventiveMaintenance: "صيانة وقائية",
        mechanicalBreakdown: "عطل ميكانيكي",
        suspensionBreakdown: "عطل في نظام التعليق",
        hydraulicBreakdown: "عطل هيدروليكي",
        bodyPaintBreakdown: "عطل في الهيكل والدهان",
        tireBreakdown: "عطل في الإطارات",
        acBreakdown: "عطل في التكييف",
        other: "أخرى",
        affectedPart: "الجزء / العنصر المتأثر",
        specifyIncidentType: "يرجى تحديد نوع الحادث",
        specifyAffectedPart: "يرجى تحديد الجزء المتأثر",

        // Transfers
        transferVehicleTitle: "نقل سيارة",
        transferInfo: "معلومات النقل",
        currentProject: "المشروع الحالي",
        transferTo: "نقل إلى",
        transferDate: "تاريخ ووقت النقل",
        selectProject: "اختر مشروع الوجهة...",
        confirmTransfer: "تأكيد النقل",
        transferSuccess: "تم نقل السيارة بنجاح!",
        transferError: "خطأ في نقل السيارة.",
        transferHistory: "سجل النقل",
        noTransfersFound: "لا يوجد سجل نقل.",
        thFromProject: "من مشروع",
        thToProject: "إلى مشروع",
        status_Transferred: "تم النقل",
        status_Returned: "تم الإرجاع",
        notifyAdmin: "إبلاغ المسؤول",
        notifyAdminSent: "إبلاغ بالإرسال",
        notifyAdminReturned: "إبلاغ بالعودة",
        notified: "تم الإبلاغ",
        notificationSent: "تم إبلاغ المسؤول.",
        deleteTransferTitle: "حذف النقل",
        deleteTransferMessage: "هل أنت متأكد أنك تريد حذف سجل النقل هذا؟ لا يمكن التراجع عن هذا الإجراء.",
        returnVehicle: "إعادة المركبة",
        returnSuccess: "تمت إعادة المركبة بنجاح!",
        returnError: "خطأ في إعادة المركبة.",

        // Admin
        adminDashboard: "لوحة تحكم المسؤول",
        allProjectsReport: "المشاريع",
        allIncidentsReport: "الحوادث",
        allVehiclesReport: "المركبات",
        viewProjectDashboard: "عرض لوحة التحكم",
        thProjectName: "اسم المشروع",
        thProjectManager: "المدير",
        thProjectId: "معرف المشروع",
        totalIncidents: "إجمالي الحوادث",
        globalVehicleSearch: "بحث شامل عن السيارات",
        searchByDoorNumberAdmin: "ابحث برقم الباب...",
        globalDriverSearch: "بحث شامل عن السائقين",
        searchByIqama: "ابحث برقم الإقامة...",
        globalSearchPlaceholder: "ابحث عن مركبة (باب/لوحة) أو شخص (إقامة)...",
        vehicleFoundIn: "تم العثور على السيارة في مشروع",
        driverFoundIn: "تم العثور على السائق في مشروع",
        personFoundIn: "تم العثور على الشخص في مشروع",
        driverNotFound: "لم يتم العثور على سائق برقم الإقامة هذا.",
        searchNotFound: "لم يتم العثور على مركبة أو شخص بهذا المعرف.",
        totalVehiclesByProject: "إجمالي السيارات حسب المشروع",
        allProjects: "جميع المشاريع",
        filterByProject: "تصفية حسب المشروع...",
        transferLog: "سجل النقل",
        transferNotifications: "إشعارات النقل",
        dismissNotification: "تجاهل",
        noNewNotifications: "لا توجد إشعارات جديدة.",
        clearAll: "مسح الكل",
        clearAllNotificationsTitle: "مسح جميع الإشعارات",
        clearAllNotificationsMessage: "هل أنت متأكد أنك تريد حذف جميع الإشعارات بشكل دائم؟",
        adminReports: "تقارير المسؤول",
        adminTransferLog: "سجل النقل",
        adminAllProjects: "المشاريع",
        adminAllMenpower: "القوى العاملة",
        adminAllMenpowerReport: "القوى العاملة",
        viewMenpower: "القوى العاملة",
        adminAllIncidents: "الحوادث",
        adminAllVehicles: "المركبات",
        adminAllDrivers: "السائقين",

        // Menpower
        menpower: "القوى العاملة",
        supervisors: "المشرفون",
        addMenpower: "إضافة قوى عاملة",
        dynamicJson: "هيكل JSON الديناميكي",
        menpowerOverview: "نظرة عامة على القوى العاملة",
        manpowerAssign: "تعيين القوى العاملة",
        addMenpowerTitle: "إضافة قوى عاملة",
        downloadTemplate: "تحميل القالب",
        downloadForemenTemplate: "تحميل قالب رؤساء العمال",
        downloadLabourTemplate: "تحميل قالب العمال",
        templateDownloadSuccess: "تم تحميل القالب بنجاح",
        supervisorInfo: "معلومات المشرف",
        supervisorName: "مشرف",
        supervisorEmpId: "معرف الموظف",
        areaLocation: "المنطقة / الموقع",
        supervisorIqama: "رقم إقامة المشرف",
        supervisorMobile: "رقم جوال المشرف",
        foremenInfo: "معلومات المراقبين",
        addForeman: "إضافة مراقب",
        foremanName: "اسم المراقب",
        foremanIqama: "إقامة المراقب",
        foremanEmpId: "معرف الموظف للمراقب",
        saveSupervisor: "حفظ المشرف",
        supervisorSaveSuccess: "تم حفظ المشرف والمراقبين بنجاح!",
        supervisorUpdateSuccess: "تم تحديث المشرف بنجاح!",
        menpowerOverviewTitle: "نظرة عامة على القوى العاملة",
        menpowerBySupervisor: "القوى العاملة حسب المشرف",
        campLabour: "عامل معسكر",
        crewman: "عامل الضاغط",
        totalLabour: "إجمالي العمالة",
        totalLabours: "إجمالي العمال",
        totalWorkforce: "إجمالي القوى العاملة",
        totalMenpower: "إجمالي القوى العاملة",
        total: "الإجمالي",
        labour: "عامل",
        labourName: "اسم العامل",
        labourIqama: "إقامة العامل",
        labourEmpId: "معرف الموظف للعامل",
        addLabour: "إضافة عامل",
        noSupervisorsFound: "لم يتم إضافة أي مشرفين بعد.",
        totalSupervisors: "إجمالي المشرفين",
        totalForemen: "إجمالي المراقبين",
        projectLevelLabour: "عمالة على مستوى المشروع",
        vehicleFleet: "أسطول السيارات",
        menpowerStatistics: "إحصائيات القوى العاملة",
        editSupervisorTitle: "تعديل المشرف",
        deleteSupervisorTitle: "حذف المشرف",
        deleteSupervisorMessage: "هل أنت متأكد أنك تريد حذف هذا المشرف وجميع المراقبين المرتبطين به؟",
        resourceClassification: "تصنيف المورد",
        assignToSupervisor: "تعيين لمشرف",
        assignToForeman: "تعيين لمراقب",
        selectSupervisor: "اختر مشرف...",
        selectForeman: "اختر مراقب...",
        personalInfo: "المعلومات الشخصية",
        saveEntry: "حفظ الإدخال",
        entrySaveSuccess: "تم حفظ إدخال القوى العاملة بنجاح!",
        entryType: "نوع الإدخال",
        selectEntryType: "اختر نوع الإدخال...",
        entryDetails: "تفاصيل الإدخال",
        foreman: "مراقب",
        personName: "الاسم",
        employeeId: "معرف الموظف",
        iqamaNumber: "رقم الإقامة",
        selectSupervisorPrompt: "أولاً، اختر مشرفًا...",
        projectOfficer: "مسؤول المشروع",
        totalOfficers: "إجمالي المسؤولين",
        viewSupervisors: "عرض المشرفين",
        supervisorDetails: "تفاصيل المشرف",
        overview: "نظرة عامة",
        foremen: "المراقبون",
        labours: "العمال",
        vehicles: "المركبات",
        reports: "التقارير",
        selectSupervisorToView: "اختر مشرفًا من القائمة لعرض تفاصيله.",
        featureComingSoon: "الميزة قادمة قريبًا.",
        labourDetails: "تفاصيل العمال",
        selectForemanPrompt: "الرجاء اختيار مراقب لعرض العمال المعينين له.",
        vehiclesLabel: "المركبات",
        showDetails: "عرض التفاصيل",
        hideDetails: "إخفاء التفاصيل",
        searchByServiceType: "ابحث حسب نوع الخدمة...",
        allSites: "كل المواقع",
        editServiceTypeTitle: "تعديل نوع الخدمة",
        newServiceType: "نوع الخدمة الجديد",
        updateServiceType: "تحديث نوع الخدمة",
        serviceTypeUpdateSuccess: "تم تحديث أنواع الخدمة بنجاح!",
        allServiceTypes: "جميع أنواع الخدمات",
        
        // Project Officers
        projectOfficersHeader: "مسؤولو المشروع",
        addProjectOfficers: "إضافة/تعديل المسؤولين",
        viewProjectOfficers: "عرض مسؤولي المشروع",
        officerRole_Project_Manager: "مدير المشروع",
        officerRole_Assistant_Project_Manager: "مساعد مدير المشروع",
        officerRole_Operation_Manager: "مدير العمليات",
        officerRole_Admin_Manager: "المدير الإداري",
        officerRole_Camp_Boss: "مسؤول السكن",
        officerRole_Fleet_Manager: "مدير الأسطول",
        officerRole_Haraka_Supervisor_1: "مشرف الحركة 1",
        officerRole_Haraka_Supervisor_2: "مشرف الحركة 2",
        officerRole_Other: "أخرى",
        officerRole: "دور المسؤول",
        officerName: "الاسم",
        officerId: "رقم هوية المسؤول",
        officerIqama: "رقم الإقامة",
        officerMobile: "رقم الجوال",
        updateOfficers: "تحديث المسؤولين",
        officersUpdateSuccess: "تم تحديث مسؤولي المشروع بنجاح!",
        exportOfficers: "تصدير تقرير المسؤولين",
        exportForemen: "تصدير جميع رؤساء العمال",
        exportLabour: "تصدير جميع العمال",
        noOfficersFound: "لم يتم إضافة أي مسؤولي مشروع بعد.",
        projectOfficersReport: "تقرير مسؤولي المشروع",
        addOfficer: "إضافة مسؤول",
        deleteOfficerTitle: "حذف المسؤول",
        deleteOfficerMessage: "هل أنت متأكد أنك تريد حذف هذا المسؤول؟",
        editOfficerTitle: "تعديل مسؤول المشروع",
        exportAllMenpower: "تصدير كل القوى العاملة",
        viewCrewmen: "عرض عمال الضاغط",
        viewCampLabours: "عرض عمال المعسكر",
        noCrewmenFound: "لم يتم العثور على عمال ضاغط.",
        noCampLaboursFound: "لم يتم العثور على عمال معسكر.",
        editLabourTitle: "تعديل العامل",
        deleteLabourTitle: "حذف العامل",
        deleteLabourMessage: "هل أنت متأكد أنك تريد حذف هذا العامل؟",
        importProjectOfficers: "استيراد مسؤولي المشروع",
        importCrewmen: "استيراد عمال الضاغط",
        importCampLabours: "استيراد عمال المعسكر",
        importSupervisors: "استيراد المشرفين",
        exportSupervisors: "تصدير تقرير المشرفين",
        assignedAreaName: "اسم المنطقة المخصصة",
        totalForman: "إجمالي المراقبين",
        searchBySupervisorNameOrIqama: "البحث بالاسم أو الإقامة...",
        noSupervisorsFoundSearch: "لم يتم إضافة أي مشرفين بعد.",
        deleteSupervisorsTitle: "حذف المشرفين",
        deleteSupervisorsMessage: "هل أنت متأكد من أنك تريد حذف المشرفين المحددين وجميع المراقبين المرتبطين بهم؟",

        // Manpower Summary Modal
        manpowerSummaryTitle: "ملخص القوى العاملة",
        selectSupervisorFirst: "أولاً اختر مشرفاً لعرض المراقبين",
        selectForemanToViewLabour: "اختر مراقباً لعرض العمال التابعين له",
        noForemenUnderSupervisor: "لا يوجد مراقبون تحت هذا المشرف",
        noLabourUnderForeman: "لا يوجد عمال تحت هذا المراقب",
        viewManpowerSummary: "عرض ملخص القوى العاملة",

        // New Vehicle History Page
        vehicleHistoryTitle: "سجل تاريخ المركبة",
        reportsPageInfo: "تعرض هذه الصفحة المركبات التي تحتاج إلى اهتمام أو تم إصلاحها مؤخرًا",
        bulkSelect: "تحديد متعدد",
        selectAll: "تحديد الكل",
        searchByDoorNumberVH: "بحث برقم الباب",
        dateFrom: "من تاريخ",
        dateTo: "إلى تاريخ",
        filterByStatusVH: "تصفية حسب الحالة",
        allStatusesVH: "جميع الحالات",
        activeVH: "نشطة",
        underIncidentVH: "تحت الحادث",
        recentlyRepairedVH: "تم إصلاحها مؤخرًا",
        clearFilters: "مسح الفلاتر",
        problematicVehiclesOverview: "نظرة عامة على المركبات المتعطلة",
        noProblematicVehicles: "جميع المركبات تعمل بشكل طبيعي - لا توجد مركبات تتطلب اهتمامًا",
        latestIncident: "آخر حادث:",
        totalIncidentsLabel: "إجمالي الحوادث",
        markAsRepaired: "تحديد كـ 'تم الإصلاح'",
        historyLog: "سجل التاريخ",
        events: "أحداث",
        noHistoryFound: "لم يتم العثور على أحداث تاريخية للمعايير المحددة.",
        createdDate: "تاريخ الإنشاء:",
        incidentTypeVH: "نوع الحادث:",
        reasonDescriptionVH: "السبب / الوصف:",
        repairDate: "تاريخ الإصلاح",
        repairedByVH: "تم الإصلاح بواسطة:",
        repairDetails: "تفاصيل الإصلاح",
        confirmDeleteHistory: "تأكيد حذف السجل الكامل",
        deleteHistoryWarning: "تحذير: لا يمكن التراجع عن هذا الإجراء.",
        deleteHistoryIncidents: "جميع حوادث المركبات المحددة",
        deleteHistoryRepairs: "جميع سجلات الإصلاح",
        deleteHistoryTransfers: "جميع سجلات النقل",
        deletePermanently: "حذف نهائي بالكامل",
        dismissActiveIncidentTitle: "تجاهل الحادث",
        dismissActiveIncidentMessage: "هل أنت متأكد أنك تريد تجاهل هذا الحادث؟ سيتم تحديد المركبة كـ 'نشطة' وسيتم إزالة سجل الحادث هذا.",
        dismissHistoryTitle: "تجاهل السجل",
        dismissHistoryMessage: "هل أنت متأكد أنك تريد تجاهل آخر سجل إصلاح؟ سيؤدي هذا إلى إزالة سجل الإصلاح والحادث المرتبط به.",
        deleteSelectedHistory: "حذف المحدد ({count})",
        deleteSelectedHistoryTitle: "حذف سجل المركبات المحددة",
        deleteSelectedHistoryMessage: "هل أنت متأكد أنك تريد حذف جميع سجلات التاريخ (الحوادث، الإصلاحات، النقل) للمركبات المحددة وعددها {count} بشكل دائم؟ لا يمكن التراجع عن هذا الإجراء.",
        dismissSelectedHistoryTitle: "حذف السجلات المحددة",
        dismissSelectedHistoryMessage: "هل أنت متأكد أنك تريد حذف السجلات المحددة وعددها {count}؟ سيؤدي هذا إلى إزالة سجلات الإصلاح والحوادث المرتبطة بها.",

        // Mark As Repaired Modal
        markVehicleActiveTitle: "تحديد المركبة كنشطة",
        vehicleInformation: "معلومات المركبة",
        currentStatus: "الحالة الحالية:",
        repairedBy: "تم الإصلاح بواسطة",
        repairedByPlaceholder: "اسم الشخص/الشركة التي قامت بالإصلاح",
        repairNotes: "ملاحظات الإصلاح (اختياري)",
        repairNotesPlaceholder: "تفاصيل إضافية حول الإصلاح المكتمل...",
        confirmRepairWarning: "بتأكيد الإصلاح، ستتم إزالة هذه المركبة من قائمة المركبات المتعطلة وستصبح نشطة مرة أخرى.",
        confirmRepair: "تأكيد الإصلاح",
        confirmed: "تم التأكيد!",
        confirming: "جاري التأكيد...",
        repairSuccessMessage: "✅ تم تأكيد إصلاح المركبة بنجاح! ستغلق النافذة...",

        // Project Names (for programmatic lookup)
// Fix: Corrected typo in translation key from 'Riad' to 'Riyadh' to match programmatic access.
        projectName_Riyadh_Site_Project: "مشروع موقع الرياض",
        projectName_Jeddah_Expansion: "توسعة جدة",
    }
};

// Banner images for Dashboard and Slideshows (excluding company logo)
export const BANNER_IMAGES: string[] = [
    '/images/Generated Image November 10, 2025 - 12_31PM.png',
    '/images/Generated Image November 10, 2025 - 12_23PM (1) copy.png',
    '/images/Generated Image November 10, 2025 - 12_23PM (1).png',
    '/images/Generated image 1.png',
    '/images/Zahran-mission.webp'
];

export const COMPANY_LOGO: string = '/images/company-logo.jpeg';